const data = [
  {
    unit: 'U1', section: 'S1', 
    words: [{ word: "ちゅうごくじん", property: "名", meaning: "中国人", },
    { word: "にほんじん", property: "名", meaning: "日本人", },
    { word: "かんこくじん", property: "名", meaning: "韩国人", },
    { word: "アメリカじん", property: "名", meaning: "美国人", },
    { word: "フランスじん", property: "名", meaning: "法国人", },
    { word: "がくせい", property: "名", meaning: "（大）学生", },
    { word: "せんせい", property: "名", meaning: "老师", },
    { word: "りゅうがくせい", property: "名", meaning: "留学生", },
    { word: "きょうじゅ", property: "名", meaning: "教授", },
    { word: "しゃいん", property: "名", meaning: "职员", },
    { word: "かいしゃいん", property: "名", meaning: "公司职员", },
    { word: "てんいん", property: "名", meaning: "店员", },
    { word: "けんしゅうせい", property: "名", meaning: "进修生", },
    { word: "きぎょう", property: "名", meaning: "企业", },
    { word: "だいがく", property: "名", meaning: "大学", },
    { word: "ちち", property: "名", meaning: "（我）父亲", },
    { word: "かちょう", property: "名", meaning: "科长", },
    { word: "しゃちょう", property: "名", meaning: "总经理，社长", },
    { word: "でむかえ", property: "名", meaning: "迎接", },
    { word: "あのひと", property: "名", meaning: "那个人", },
    { word: "わたし", property: "代", meaning: "我", },
    { word: "あなた", property: "代", meaning: "你", },
    { word: "どうも", property: "副", meaning: "非常，很", },
    { word: "はい", property: "叹", meaning: "哎，是的", },
    { word: "いいえ", property: "叹", meaning: "不，不是", },
    { word: "あっ", property: "叹", meaning: "哎，哎呀", },
    { word: "り", property: "专", meaning: "李", },
    { word: "おう", property: "专", meaning: "王", },
    { word: "ちょう", property: "专", meaning: "张", },
    { word: "もり", property: "专", meaning: "森", },
    { word: "はやし", property: "专", meaning: "林", },
    { word: "おの", property: "专", meaning: "小野", },
    { word: "よしだ", property: "专", meaning: "吉田", },
    { word: "たなか", property: "专", meaning: "田中", },
    { word: "なかむら", property: "专", meaning: "中村", },
    { word: "たろう", property: "专", meaning: "太郎", },
    { word: "キム", property: "专", meaning: "金", },
    { word: "デュポン", property: "专", meaning: "迪蓬", },
    { word: "スミス", property: "专", meaning: "史密斯", },
    { word: "ジョンソン", property: "专", meaning: "约翰逊", },
    { word: "ちゅうごく", property: "专", meaning: "中国", },
    { word: "こんにちは", property: "短语", meaning: "你好", },
    { word: "すみません", property: "短语", meaning: "对不起，请问", },
    { word: "どうぞ", property: "短语", meaning: "请", },
    { word: "よろしくおねがいします", property: "短语", meaning: "请多关照", },
    { word: "はじめまして", property: "短语", meaning: "初次见面", },
    { word: "こちらこそ", property: "短语", meaning: "我才要，请您", },
    { word: "そうです", property: "短语", meaning: "是这样", },
    { word: "ちがいます", property: "短语", meaning: "不是", },
    { word: "わかりません", property: "短语", meaning: "不知道", },
    { word: "どうもすみません", property: "短语", meaning: "实在对不起", }]
    ,
    exercises: [
      {
        question: "ー李さんは（　）ですか。\nーはい、学生です。",
        options: [
          { op: "A", value: "中国人", },
          { op: "B", value: "日本人", },
          { op: "C", value: "学生", },
          { op: "D", value: "先生", },
        ],
        correctAns: ["C",]
      },
      {
        question: "ーあなたは  李さんですか。\n－（　）。",
        options: [
          { op: "A", value: "はい、李さんです", },
          { op: "B", value: "いいえ、そうです", },
          { op: "C", value: "はい、李です", },
          { op: "D", value: "いいえ、李です", },
        ],
        correctAns: ["C",]
      },
      {
        question: "ーあなたは  小野さんですか。－（　）。",
        options: [
          { op: "A", value: "はい、李です", },
          { op: "B", value: "いいえ、小野じゃありません", },
          { op: "C", value: "はい、小野じゃです。", },
          { op: "D", value: "いいえ、そうです", },
        ],
        correctAns: ["B",]
      },
      {
        question: "ーあなたは  大学（　）先生ですか。\n－はい、そうです。",
        options: [
          { op: "A", value: "の", },
          { op: "B", value: "に", },
          { op: "C", value: "は", },
          { op: "D", value: "では", },
        ],
        correctAns: ["A",]
      },
      {
        question: "ーあなたは  中村さんですか。\n－はい、（）。",
        options: [
          { op: "A", value: "わたしは  村上です", },
          { op: "B", value: "あなたは  村上です", },
          { op: "C", value: "わたしは  中村です", },
          { op: "D", value: "あなたは  中村です", },
        ],
        correctAns: ["C",]
      },
      {
        question: "ーはじめまして、李です、（　）。\n ーはじめまして。",
        options: [
          { op: "A", value: "こちらこそ", },
          { op: "B", value: "わかりません", },
          { op: "C", value: "そうです", },
          { op: "D", value: "よろしくおねがいします", },
        ],
        correctAns: ["D",]
      },
      {
        question: "ーどうぞよろしく。\n－（）、よろしく  おねがいします。",
        options: [
          { op: "A", value: "わかりません", },
          { op: "B", value: "こちらこそ", },
          { op: "C", value: "そうです", },
          { op: "D", value: "すみません", },
        ],
        correctAns: ["B",]
      },
      {
        question: "（　）、すみません。",
        options: [
          { op: "A", value: "あっ", },
          { op: "B", value: "はっ", },
          { op: "C", value: "の", },
          { op: "D", value: "えっ", },
        ],
        correctAns: ["A",]
      },
    ],
  },
  {
  unit: "U1", section: "S2",    
  words: [{ word: "ざっし", property: "名", meaning: "杂志", },
  { word: "じしょ", property: "名", meaning: "词典", },
  { word: "カメラ", property: "名", meaning: "照相机", },
  { word: "テレビ", property: "名", meaning: "电视机", },
  { word: "パソコン", property: "名", meaning: "个人电脑", },
  { word: "ラジオ", property: "名", meaning: "收音机", },
  { word: "でんわ", property: "名", meaning: "电话", },
  { word: "つくえ", property: "名", meaning: "桌子，书桌", },
  { word: "いす", property: "名", meaning: "椅子", },
  { word: "かぎ", property: "名", meaning: "钥匙，锁", },
  { word: "とけい", property: "名", meaning: "钟，表", },
  { word: "てちょう", property: "名", meaning: "记事本", },
  { word: "しゃしん", property: "名", meaning: "照片", },
  { word: "くるま", property: "名", meaning: "车", },
  { word: "じてんしゃ", property: "名", meaning: "自行车", },
  { word: "おみやげ", property: "名", meaning: "礼物", },
  { word: "めいさんひん", property: "名", meaning: "特产，名产", },
  { word: "シルク", property: "名", meaning: "丝绸", },
  { word: "ハンカチ", property: "名", meaning: "手绢", },
  { word: "かいしゃ", property: "名", meaning: "公司", },
  { word: "かた", property: "名", meaning: "（敬称）位，人", },
  { word: "ひと", property: "名", meaning: "人", },
  { word: "かぞく", property: "名", meaning: "家人，家属", },
  { word: "はは", property: "名", meaning: "（我）母亲", },
  { word: "おかあさん", property: "名", meaning: "母亲", },
  { word: "にほんご", property: "名", meaning: "日语", },
  { word: "ちゅうごくご", property: "名", meaning: "汉语，中文", },
  { word: "これ", property: "代", meaning: "这，这个", },
  { word: "それ", property: "代", meaning: "那，那个", },
  { word: "あれ", property: "代", meaning: "那，那个", },
  { word: "どれ", property: "疑", meaning: "哪个", },
  { word: "なん", property: "疑", meaning: "什么", },
  { word: "だれ", property: "疑", meaning: "谁", },
  { word: "どなた", property: "疑", meaning: "哪位", },
  { word: "この", property: "连体", meaning: "这，这个", },
  { word: "その", property: "连体", meaning: "那，那个", },
  { word: "あの", property: "连体", meaning: "那，那个", },
  { word: "どの", property: "连体", meaning: "哪个", },
  { word: "えっ", property: "叹", meaning: "啊", },
  { word: "わあ", property: "叹", meaning: "哇", },
  { word: "ええ", property: "叹", meaning: "（应答）嗯，是", },
  { word: "ながしま", property: "专", meaning: "长岛", },
  { word: "にほん", property: "专", meaning: "日本", },
  { word: "ロンドン", property: "专", meaning: "伦敦", },
  { word: "ありがとうございます", property: "短语", meaning: "谢谢", },
  { word: "おいくつ", property: "短语", meaning: "多大", },
  { word: "そふ", property: "名", meaning: "（我）祖父", },
  { word: "そぼ", property: "名", meaning: "（我）祖母", },
  { word: "りょうしん", property: "名", meaning: "（我）父母", },
  { word: "ちち", property: "名", meaning: "（我）父亲", },
  { word: "はは", property: "名", meaning: "（我）母亲", },
  { word: "むすこ", property: "名", meaning: "（我）儿子", },
  { word: "むすめ", property: "名", meaning: "（我）女儿", },
  { word: "きょうだい", property: "名", meaning: "（我）兄弟姐妹", },
  { word: "あに", property: "名", meaning: "（我）哥哥", },
  { word: "あね", property: "名", meaning: "（我）姐姐", },
  { word: "おとうと", property: "名", meaning: "（我）弟弟", },
  { word: "いもうと", property: "名", meaning: "（我）妹妹", },
  { word: "おじ", property: "名", meaning: "（我）伯伯，叔叔，舅舅，姑父", },
  { word: "おば", property: "名", meaning: "（我）伯母，婶婶，姑姑，舅妈", },
  { word: "おじいさん", property: "名", meaning: "（别人）祖父", },
  { word: "おばあさん", property: "名", meaning: "（别人）祖母", },
  { word: "ごりょうしん", property: "名", meaning: "（别人）父母", },
  { word: "おとうさん", property: "名", meaning: "（别人）父亲", },
  { word: "おかあさん", property: "名", meaning: "（别人）母亲", },
  { word: "むすこさん", property: "名", meaning: "（别人）儿子", },
  { word: "むすめさん", property: "名", meaning: "（别人）女儿", },
  { word: "ごきょうだい", property: "名", meaning: "（别人）兄弟姐妹", },
  { word: "おにいさん", property: "名", meaning: "（别人）哥哥", },
  { word: "おねえさん", property: "名", meaning: "（别人）姐姐", },
  { word: "おとうとさん", property: "名", meaning: "（别人）弟弟", },
  { word: "いもうとさん", property: "名", meaning: "（别人）妹妹", },
  { word: "おじさん", property: "名", meaning: "（别人）伯伯，叔叔，舅舅，姑父", },
  { word: "おばさん", property: "名", meaning: "（别人）伯母，婶婶，姑姑，舅妈", },
  { word: "れい／ぜろ", property: "数", meaning: "0（2种）", },
  { word: "いち", property: "数", meaning: "1", },
  { word: "に", property: "数", meaning: "2", },
  { word: "さん", property: "数", meaning: "3", },
  { word: "し／よん", property: "数", meaning: "4（2种）", },
  { word: "ご", property: "数", meaning: "5", },
  { word: "ろく", property: "数", meaning: "6", },
  { word: "しち／なな", property: "数", meaning: "7（2种）", },
  { word: "はち", property: "数", meaning: "8", },
  { word: "く／きゅう", property: "数", meaning: "9（2种）", },
  { word: "じゅう", property: "数", meaning: "10", },
  { word: "じゅういち", property: "数", meaning: "11", },
  { word: "じゅうに", property: "数", meaning: "12", },
  { word: "じゅうさん", property: "数", meaning: "13", },
  { word: "じゅうし／じゅうよん", property: "数", meaning: "14（2种）", },
  { word: "じゅうご", property: "数", meaning: "15", },
  { word: "じゅうろく", property: "数", meaning: "16", },
  { word: "じゅうしち／じゅうなな", property: "数", meaning: "17（2种）", },
  { word: "じゅうはち", property: "数", meaning: "18", },
  { word: "じゅうく／じゅうきゅう", property: "数", meaning: "19（2种）", },
  { word: "にじゅう", property: "数", meaning: "20", },
  { word: "さんじゅう", property: "数", meaning: "30", },
  { word: "よんじゅう", property: "数", meaning: "40", },
  { word: "ごじゅう", property: "数", meaning: "50", },
  { word: "ろくじゅう", property: "数", meaning: "60", },
  { word: "ななじゅう", property: "数", meaning: "70", },
  { word: "はちじゅう", property: "数", meaning: "80", },
  { word: "きゅうじゅう", property: "数", meaning: "90", },
  { word: "ひやく", property: "数", meaning: "100", },
  { word: "れいてんいち", property: "数", meaning: "0.1", },
  { word: "さんぶんのに", property: "数", meaning: "三分之二", },
  { word: "れい／ぜろ", property: "数", meaning: "0（2种）", },
  { word: "いち", property: "数", meaning: "1", },
  { word: "に", property: "数", meaning: "2", },
  { word: "さん", property: "数", meaning: "3", },
  { word: "し／よん", property: "数", meaning: "4（2种）", },
  { word: "ご", property: "数", meaning: "5", },
  { word: "ろく", property: "数", meaning: "6", },
  { word: "しち／なな", property: "数", meaning: "7（2种）", },
  { word: "はち", property: "数", meaning: "8", },
  { word: "く／きゅう", property: "数", meaning: "9（2种）", },
  { word: "じゅう", property: "数", meaning: "10", },
  { word: "じゅういち", property: "数", meaning: "11", },
  { word: "じゅうに", property: "数", meaning: "12", },
  { word: "じゅうさん", property: "数", meaning: "13", },
  { word: "じゅうし／じゅうよん", property: "数", meaning: "14（2种）", },
  { word: "じゅうご", property: "数", meaning: "15", },
  { word: "じゅうろく", property: "数", meaning: "16", },
  { word: "じゅうしち／じゅうなな", property: "数", meaning: "17（2种）", },
  { word: "じゅうはち", property: "数", meaning: "18", },
  { word: "じゅうく／じゅうきゅう", property: "数", meaning: "19（2种）", },
  { word: "にじゅう", property: "数", meaning: "20", },
  { word: "さんじゅう", property: "数", meaning: "30", },
  { word: "よんじゅう", property: "数", meaning: "40", },
  { word: "ごじゅう", property: "数", meaning: "50", },
  { word: "ろくじゅう", property: "数", meaning: "60", },
  { word: "ななじゅう", property: "数", meaning: "70", },
  { word: "はちじゅう", property: "数", meaning: "80", },
  { word: "きゅうじゅう", property: "数", meaning: "90", },
  { word: "ひやく", property: "数", meaning: "100", },
  { word: "れいてんいち", property: "数", meaning: "0.1", },
  { word: "さんぶんのに", property: "数", meaning: "三分之二", },
  { word: "れい／ぜろ", property: "数", meaning: "0（2种）", },
  { word: "いち", property: "数", meaning: "1", },
  { word: "に", property: "数", meaning: "2", },
  { word: "さん", property: "数", meaning: "3", },
  { word: "し／よん", property: "数", meaning: "4（2种）", },
  { word: "ご", property: "数", meaning: "5", },
  { word: "ろく", property: "数", meaning: "6", },
  { word: "しち／なな", property: "数", meaning: "7（2种）", },
  { word: "はち", property: "数", meaning: "8", },
  { word: "く／きゅう", property: "数", meaning: "9（2种）", },
  { word: "じゅう", property: "数", meaning: "10", },
  { word: "じゅういち", property: "数", meaning: "11", },
  { word: "じゅうに", property: "数", meaning: "12", },
  { word: "じゅうさん", property: "数", meaning: "13", },
  { word: "じゅうし／じゅうよん", property: "数", meaning: "14（2种）", },
  { word: "じゅうご", property: "数", meaning: "15", },
  { word: "じゅうろく", property: "数", meaning: "16", },
  { word: "じゅうしち／じゅうなな", property: "数", meaning: "17（2种）", },
  { word: "じゅうはち", property: "数", meaning: "18", },
  { word: "じゅうく／じゅうきゅう", property: "数", meaning: "19（2种）", },
  { word: "にじゅう", property: "数", meaning: "20", },
  { word: "さんじゅう", property: "数", meaning: "30", },
  { word: "よんじゅう", property: "数", meaning: "40", },
  { word: "ごじゅう", property: "数", meaning: "50", },
  { word: "ろくじゅう", property: "数", meaning: "60", },
  { word: "ななじゅう", property: "数", meaning: "70", },
  { word: "はちじゅう", property: "数", meaning: "80", },
  { word: "きゅうじゅう", property: "数", meaning: "90", },
  { word: "ひやく", property: "数", meaning: "100", },
  { word: "れいてんいち", property: "数", meaning: "0.1", },
  { word: "さんぶんのに", property: "数", meaning: "三分之二", },
  ],
  exercises: [
    { 
      question: 'これは　（かさ）です。', 
      options: [
        { op: 'A', value: '靴', }, 
        { op: 'B', value: '本', }, 
        { op: 'C', value: '傘', }, 
        { op: 'D', value: '机', }],
      correctAns: ['C'] },
    { 
      question: 'それは　（じしょ）です。', 
      options: [
        { op: 'A', value: '新聞', }, 
        { op: 'B', value: '辞書', }, 
        { op: 'C', value: '雑誌', }, 
        { op: 'D', value: '時計', }], 
      correctAns: ['B'] },
    { 
      question: 'あれは　だれの（しゃしん）ですか。', 
      options: [
        { op: 'A', value: '写真', }, 
        { op: 'B', value: '時計', }, 
        { op: 'C', value: '車', }, 
        { op: 'D', value: '照片', }], 
      correctAns: ['A'] },
    { 
      question: 'これは　（なん）ですか。', 
      options: [
        { op: 'A', value: '母', }, 
        { op: 'B', value: '誰', }, 
        { op: 'C', value: '人', }, 
        { op: 'D', value: '何', }], 
      correctAns: ['D'] },
    { 
      question: 'これは　わたしの　（自転車）です。', 
      options: [
        { op: 'A', value: 'してんしゃ', }, 
        { op: 'B', value: 'じてんしゃ', }, 
        { op: 'C', value: 'しでんしゃ', }, 
        { op: 'D', value: 'じでんしゃ', }], 
      correctAns: ['B'] },
    { question: 'これは　（お土産）です、どうぞ。', options: [{ op: 'A', value: 'おみやげ', }, { op: 'B', value: 'おみやけ', }, { op: 'C', value: 'おとさん', }, { op: 'D', value: 'おどさん', }], correctAns: ['A'] },
    { question: 'あれは　李さんの　（鉛筆）です。', options: [{ op: 'A', value: 'えんひつ', }, { op: 'B', value: 'せんひつ', }, { op: 'C', value: 'えんぴつ', }, { op: 'D', value: 'せんぴつ', }], correctAns: ['C'] },
    { question: 'わたしの　（母）は　40歳です。', options: [{ op: 'A', value: 'ちち', }, { op: 'B', value: 'はは', }, { op: 'C', value: 'かあ', }, { op: 'D', value: 'とう', }], correctAns: ['B'] },
    { question: 'ー小野さんの　本は　（　）ですか。\nーこれです。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'なに', }, { op: 'C', value: 'どれ', }, { op: 'D', value: 'だれ', }], correctAns: ['C'] },
    { question: 'ーこれは　お土産です、どうぞ。\n－（　）', options: [{ op: 'A', value: 'どうも　すみません', }, { op: 'B', value: 'はい、どうぞ', }, { op: 'C', value: 'はい、そうです', }, { op: 'D', value: 'ありがとうございます', }], correctAns: ['D'] },
    { question: 'ーこれは中国の名産品です、（　）。', options: [{ op: 'A', value: 'どうぞ', }, { op: 'B', value: 'どうも', }, { op: 'C', value: 'どう', }, { op: 'D', value: 'こちらこそ', }], correctAns: ['A'] },
    { question: 'ーこれは　だれのパソコンですか。\n－（　）は　李さんのです。', options: [{ op: 'A', value: 'これ', }, { op: 'B', value: 'それ', }, { op: 'C', value: 'あれ', }, { op: 'D', value: 'どれ', }], correctAns: ['B'] },
    { question: 'ーあなたは（　）ですか。\nー26歳です。', options: [{ op: 'A', value: 'おいくつ', }, { op: 'B', value: 'なん', }, { op: 'C', value: 'だれ', }, { op: 'D', value: 'どの', }], correctAns: ['A'] },
    { question: 'ーこれは　（　）の　カメラですか。\nーわたしのです。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'なに', }, { op: 'C', value: 'どれ', }, { op: 'D', value: 'だれ', }], correctAns: ['D'] },
    { question: 'ーあれは　雑誌ですか。\nーいいえ、（　）は　辞書です。', options: [{ op: 'A', value: 'これ', }, { op: 'B', value: 'それ', }, { op: 'C', value: 'あれ', }, { op: 'D', value: 'どれ', }], correctAns: ['C'] },
    { question: 'ーわたしは学生です。\nー（　）。ー学生です。　', options: [{ op: 'A', value: 'はっ', }, { op: 'B', value: 'えっ', }, { op: 'C', value: 'あっ', }, { op: 'D', value: 'ええ', }], correctAns: ['B'] },
    { question: 'ーこれは　（　）ですか。\nーそれは　かばんです。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'なに', }, { op: 'C', value: 'どれ', }, { op: 'D', value: 'だれ', }], correctAns: ['A'], },
  ],
  },
  {
    unit: "U1", section: "S3",
    words:[{ word: "デパート", property: "名", meaning: "百货商店", },
    { word: "しょくどう", property: "名", meaning: "食堂", },
    { word: "ゆうびんきょく", property: "名", meaning: "邮局", },
    { word: "ぎんこう", property: "名", meaning: "银行", },
    { word: "としょかん", property: "名", meaning: "图书馆", },
    { word: "マンション", property: "名", meaning: "（高级）公寓", },
    { word: "ホテル", property: "名", meaning: "宾馆", },
    { word: "コンビニ", property: "名", meaning: "便利店", },
    { word: "きっさてん", property: "名", meaning: "咖啡馆", },
    { word: "びょういん", property: "名", meaning: "医院", },
    { word: "ほんや", property: "名", meaning: "书店", },
    { word: "レストラン", property: "名", meaning: "餐馆，西餐馆", },
    { word: "ビル", property: "名", meaning: "大楼，大厦", },
    { word: "たてもの", property: "名", meaning: "大楼，建筑物", },
    { word: "うりば", property: "名", meaning: "柜台，出售处", },
    { word: "トイレ", property: "名", meaning: "厕所，盥洗室", },
    { word: "いりぐち", property: "名", meaning: "入口", },
    { word: "じむしょ", property: "名", meaning: "事务所，办事处", },
    { word: "うけつけ", property: "名", meaning: "接待处", },
    { word: "バーゲンかいじょう", property: "名", meaning: "降价处理大卖场", },
    { word: "エスカレーター", property: "名", meaning: "自动扶梯", },
    { word: "ふく", property: "名", meaning: "衣服", },
    { word: "コート", property: "名", meaning: "风衣，大水", },
    { word: "デジカメ", property: "名", meaning: "数码相机", },
    { word: "くに", property: "名", meaning: "国，国家", },
    { word: "ちず", property: "名", meaning: "地图", },
    { word: "となり", property: "名", meaning: "旁边", },
    { word: "しゅうへん", property: "名", meaning: "附近，周边", },
    { word: "きょう", property: "名", meaning: "今天", },
    { word: "すいようび", property: "名", meaning: "星期三", },
    { word: "もくようび", property: "名", meaning: "星期四", },
    { word: "ここ", property: "代", meaning: "这里，这儿", },
    { word: "そこ", property: "代", meaning: "那里，那儿", },
    { word: "あそこ", property: "代", meaning: "那里，那儿", },
    { word: "こちら", property: "代", meaning: "这儿，这边", },
    { word: "そちら", property: "代", meaning: "那儿，那边", },
    { word: "あちら", property: "代", meaning: "那儿，那边", },
    { word: "どこ", property: "疑", meaning: "哪里，哪儿", },
    { word: "どちら", property: "疑", meaning: "哪儿，哪边", },
    { word: "あのう", property: "叹", meaning: "请问，对不起", },
    { word: "シャンハイ", property: "专", meaning: "上海", },
    { word: "とうきょう", property: "专", meaning: "东京", },
    { word: "いくら", property: "短语", meaning: "多少钱", },
    { word: " ひゃく", property: "数", meaning: "100", },
    { word: "にひゃく", property: "数", meaning: "200", },
    { word: "さんびゃく", property: "数", meaning: "300", },
    { word: "よんひゃく", property: "数", meaning: "400", },
    { word: "ごひゃく", property: "数", meaning: "500", },
    { word: "ろっぴゃく", property: "数", meaning: "600", },
    { word: "ななひゃく", property: "数", meaning: "700", },
    { word: "なっぴゃく", property: "数", meaning: "800", },
    { word: "きゅうひゃく", property: "数", meaning: "900", },
    { word: "さん", property: "数", meaning: "1000", },
    { word: "にせん", property: "数", meaning: "2000", },
    { word: "さんぜん", property: "数", meaning: "3000", },
    { word: "よんせん", property: "数", meaning: "4000", },
    { word: "ごせん", property: "数", meaning: "5000", },
    { word: "ろくせん", property: "数", meaning: "6000", },
    { word: "ななせん", property: "数", meaning: "7000", },
    { word: "はっせん", property: "数", meaning: "8000", },
    { word: "きゅうせん", property: "数", meaning: "9000", },
    { word: "いちまん", property: "数", meaning: "10000", },
    { word: "じゅうまん", property: "数", meaning: "100000", },
    { word: "ひゃくまん", property: "数", meaning: "1000000", },
    { word: "いっせんまん", property: "数", meaning: "10000000", },
    { word: "いちおく", property: "数", meaning: "100000000", },
    { word: "きゅうせんに", property: "数", meaning: "9002", },
    { word: "きゅうせんにじゅう", property: "数", meaning: "9020", },
    { word: "きゅうせんにひゃく", property: "数", meaning: "9200", }],
  exercises:[{ question: 'ーすみません、（ほんや）は　どこですか。', options: [{ op: 'A', value: '八百屋', }, { op: 'B', value: '本屋', }, { op: 'C', value: '翻訳', }, { op: 'D', value: '銀行', }], correctAns: ['B'] },
{ question: 'ここは　（きっさてん）です。', options: [{ op: 'A', value: '図書館', }, { op: 'B', value: '食堂', }, { op: 'C', value: '傘店', }, { op: 'D', value: '喫茶店', }], correctAns: ['D'] },
{ question: '銀行の　（となり）は　図書館です。', options: [{ op: 'A', value: '隣', }, { op: 'B', value: '辺', }, { op: 'C', value: '右', }, { op: 'D', value: '左', }], correctAns: ['A'] },
{ question: '今日は　（すいようび）ですか。', options: [{ op: 'A', value: '金曜日', }, { op: 'B', value: '木曜日', }, { op: 'C', value: '日曜日', }, { op: 'D', value: '水曜日', }], correctAns: ['D'] },
{ question: 'ーあのう、（売り場）は　どこですか。', options: [{ op: 'A', value: 'いりくち', }, { op: 'B', value: 'はいりくち', }, { op: 'C', value: 'うりば', }, { op: 'D', value: 'うりは', }], correctAns: ['C'] },
{ question: 'ー東京の　（地図）は　どこですか。', options: [{ op: 'A', value: 'ちす', }, { op: 'B', value: 'ぢす', }, { op: 'C', value: 'ちず', }, { op: 'D', value: 'ぢず', }], correctAns: ['C'] },
{ question: '昨日は　（木曜日）です。', options: [{ op: 'A', value: 'もうようび', }, { op: 'B', value: 'もくようび', }, { op: 'C', value: 'もうようひ', }, { op: 'D', value: 'もくゆうひ', }], correctAns: ['B'] },
{ question: '（食堂）は　このビルの　3階です。', options: [{ op: 'A', value: 'しょくどう', }, { op: 'B', value: 'しょうどう', }, { op: 'C', value: 'しょくとう', }, { op: 'D', value: 'しょうとう', }], correctAns: ['A'] },
{ question: 'ーホテルは　（　）ですか。\n－そこです。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'どれ', }, { op: 'C', value: 'だれ', }, { op: 'D', value: 'どこ', }], correctAns: ['D'] },
{ question: 'ーあのひとは　（　）ですか。\nー小野さんです。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'どれ', }, { op: 'C', value: 'だれ', }, { op: 'D', value: 'どこ', }], correctAns: ['C'] },
{ question: 'ーあなたの　傘は　（　）ですか。\n－これです。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'どれ', }, { op: 'C', value: 'だれ', }, { op: 'D', value: 'どこ', }], correctAns: ['B'] },
{ question: 'ーあれは　（　）ですか。\nーあれは　病院です。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'どれ', }, { op: 'C', value: 'だれ', }, { op: 'D', value: 'どこ', }], correctAns: ['A'] },
{ question: 'ー病院は　どちらですか。\n－（　）。', options: [{ op: 'A', value: 'あらちです。', }, { op: 'B', value: 'あちらです。', }, { op: 'C', value: 'あのうです', }, { op: 'D', value: 'どちらです。', }], correctAns: ['B'] },
{ question: 'ーここは　病院です（　）、銀行ですか。', options: [{ op: 'A', value: 'か', }, { op: 'B', value: 'が', }, { op: 'C', value: 'は', }, { op: 'D', value: 'の', }], correctAns: ['A'] },
{ question: 'ー（　）、すみません。\n－何ですか。', options: [{ op: 'A', value: 'あの', }, { op: 'B', value: 'その', }, { op: 'C', value: 'あのう', }, { op: 'D', value: 'そのう', }], correctAns: ['C'] },
{ question: 'ーこの雑誌（　）　いくらですか。', options: [{ op: 'A', value: 'か', }, { op: 'B', value: 'も', }, { op: 'C', value: 'は', }, { op: 'D', value: 'の', }], correctAns: ['C']}],
  },
  {
    unit: "U1", section: "S4",
    words: [{ word: "へや", property: "名", meaning: "房间，屋子", },
    { word: "にわ", property: "名", meaning: "院子", },
    { word: "いえ", property: "名", meaning: "家", },
    { word: "いま", property: "名", meaning: "起居室", },
    { word: "れいぞうこ", property: "名", meaning: "冰箱", },
    { word: "かべ", property: "名", meaning: "墙壁", },
    { word: "スイッチ", property: "名", meaning: "开关", },
    { word: "ほんだな", property: "名", meaning: "书架", },
    { word: "ベッド", property: "名", meaning: "床", },
    { word: "ねこ", property: "名", meaning: "猫", },
    { word: "いぬ", property: "名", meaning: "狗", },
    { word: "はこ", property: "名", meaning: "盒子，箱子", },
    { word: "めがね", property: "名", meaning: "眼镜", },
    { word: "ビデオ", property: "名", meaning: "录像机", },
    { word: "サッカーボール", property: "名", meaning: "足球", },
    { word: "ビール", property: "名", meaning: "啤酒", },
    { word: "ウイスキー", property: "名", meaning: "威士忌", },
    { word: "こども", property: "名", meaning: "孩子，小孩", },
    { word: "きょうだい", property: "名", meaning: "兄弟姐妹", },
    { word: "りょうしん", property: "名", meaning: "父母，双亲", },
    { word: "いもうと", property: "名", meaning: "妹妹", },
    { word: "おとこ", property: "名", meaning: "男", },
    { word: "おんな", property: "名", meaning: "女", },
    { word: "せいと", property: "名", meaning: "学生", },
    { word: "うえ", property: "名", meaning: "上面", },
    { word: "そと", property: "名", meaning: "外面", },
    { word: "なか", property: "名", meaning: "里面，内部，中间", },
    { word: "した", property: "名", meaning: "下面", },
    { word: "まえ", property: "名", meaning: "前，前面", },
    { word: "うしろ", property: "名", meaning: "后，后面", },
    { word: "ちかく", property: "名", meaning: "附近，近旁", },
    { word: "ばしょ", property: "名", meaning: "所在地，地方，场所", },
    { word: "きょうしつ", property: "名", meaning: "教室", },
    { word: "かいぎしつ", property: "名", meaning: "会议室", },
    { word: "としょしつ", property: "名", meaning: "图书室", },
    { word: "こうえん", property: "名", meaning: "公园", },
    { word: "はなや", property: "名", meaning: "花店", },
    { word: "ばいてん", property: "名", meaning: "小卖部，售货亭", },
    { word: "えき", property: "名", meaning: "车站", },
    { word: "ちかてつ", property: "名", meaning: "地铁", },
    { word: "き", property: "名", meaning: "树，树木", },
    { word: "ひとりぐらし", property: "名", meaning: "单身生活", },
    { word: "あります", property: "动1", meaning: "有，在（非志愿者）", },
    { word: "います", property: "动2", meaning: "有，在（具志愿者）", },
    { word: "ええと", property: "叹", meaning: "啊，嗯", },
    { word: "よこはま", property: "专", meaning: "横滨", },
    { word: "なごや", property: "专", meaning: "名古屋", },
    { word: "おおさか", property: "专", meaning: "大阪", },
    { word: "たてもの", property: "名", meaning: "大楼（平假名）", },
    { word: "ビル", property: "名", meaning: "大楼（片假名）", },
    { word: "えいがかん", property: "名", meaning: "电影院", },
    { word: "びじゅつかん", property: "名", meaning: "美术馆", },
    { word: "たいいくかん", property: "名", meaning: "体育馆", },
    { word: "はくぶつかん", property: "名", meaning: "博物馆", },
    { word: "としょかん", property: "名", meaning: "图书馆", },
    { word: "こうえん", property: "名", meaning: "公园", },
    { word: "どうぶつえん", property: "名", meaning: "动物园", },
    { word: "ゆうえんち", property: "名", meaning: "游乐园", },
    { word: "えき", property: "名", meaning: "车站", },
    { word: "くうこう", property: "名", meaning: "机场", },
    { word: "しやくしょ", property: "名", meaning: "市政所", },
    { word: "しょうぼうしょ", property: "名", meaning: "消防所", },
    { word: "けいさつしょ", property: "名", meaning: "警察局", },
    { word: "こうばん", property: "名", meaning: "派出所", },
    { word: "びょういん", property: "名", meaning: "医院", },
    { word: "ぎんこう", property: "名", meaning: "银行", },
    { word: "ゆうびんきょく", property: "名", meaning: "邮局", },
    { word: "こうじょう", property: "名", meaning: "工厂", },
    { word: "げきじょう", property: "名", meaning: "剧场", },
    { word: "ちゅうしゃじょう", property: "名", meaning: "停车场", },
    { word: "がっこう", property: "名", meaning: "学校", },
    { word: "おみせ", property: "名", meaning: "商店", },
    { word: "ほんや", property: "名", meaning: "书店", },
    { word: "やおや", property: "名", meaning: "蔬菜店", },
    { word: "にくや", property: "名", meaning: "肉店", },
    { word: "さかなや", property: "名", meaning: "鱼店", },
    { word: "そばや", property: "名", meaning: "荞麦面店", },
    { word: "とこや", property: "名", meaning: "理发店", },
    { word: "やっきょく", property: "名", meaning: "药店", },
    { word: "きっさてん", property: "名", meaning: "咖啡馆", },
    { word: "ホテル", property: "名", meaning: "宾馆", },
    { word: "デパート", property: "名", meaning: "百货商店", },
    { word: "スーパー", property: "名", meaning: "超市", },
    { word: "コンビニ", property: "名", meaning: "便利店", },
    { word: "レストラン", property: "名", meaning: "餐馆", },
    { word: "ガソリンスタンド", property: "名", meaning: "加油站", }],
    exercises:
    [{ question: '（にわ）に　本が　あります。', options: [{ op: 'A', value: '家', }, { op: 'B', value: '居間', }, { op: 'C', value: '部屋', }, { op: 'D', value: '庭', }], correctAns: ['D'] },
{ question: '本棚の　上に　（はこ）が　あります。', options: [{ op: 'A', value: '箱', }, { op: 'B', value: '犬', }, { op: 'C', value: '猫', }, { op: 'D', value: '眼鏡', }], correctAns: ['A'] },
{ question: '食堂の　隣に　（としょしつ）が　あります。', options: [{ op: 'A', value: '図書館', }, { op: 'B', value: '図書室', }, { op: 'C', value: '公園', }, { op: 'D', value: '場所', }], correctAns: ['B'] },
{ question: 'ベッドの　上に　（こども）　が　います。', options: [{ op: 'A', value: '妹', }, { op: 'B', value: '弟', }, { op: 'C', value: '子供', }, { op: 'D', value: '息子', }], correctAns: ['C'] },
{ question: 'ーご（兄弟）が　いますか。\nーはい、妹が　います。', options: [{ op: 'A', value: 'きゅうたい', }, { op: 'B', value: 'きょうたい', }, { op: 'C', value: 'きゅうだい', }, { op: 'D', value: 'きょうだい', }], correctAns: ['D'] },
{ question: '近くに　（地下鉄）が　あります。', options: [{ op: 'A', value: 'ちかてつ', }, { op: 'B', value: 'ちがてつ', }, { op: 'C', value: 'ちかでつ', }, { op: 'D', value: 'ちがでつ', }], correctAns: ['A'] },
{ question: 'わたしの　（両親）は　東京に　います。', options: [{ op: 'A', value: 'きょうたい', }, { op: 'B', value: 'きょうだい', }, { op: 'C', value: 'りょうしん', }, { op: 'D', value: 'りょしん', }], correctAns: ['C'] },
{ question: 'あの　（男）の子は　生徒です。', options: [{ op: 'A', value: 'おんな', }, { op: 'B', value: 'おとこ', }, { op: 'C', value: 'おとめ', }, { op: 'D', value: 'おとな', }], correctAns: ['B'] },
{ question: '部屋に　ねこ（　）。', options: [{ op: 'A', value: 'が　あります', }, { op: 'B', value: 'が　います', }, { op: 'C', value: 'に　あります', }, { op: 'D', value: 'に　います', }], correctAns: ['B'] },
{ question: '図書館は　どこ（　）か。', options: [{ op: 'A', value: 'が　あります', }, { op: 'B', value: 'が　います', }, { op: 'C', value: 'に　あります', }, { op: 'D', value: 'に　います', }], correctAns: ['C'] },
{ question: 'にわに　犬（　）　猫が　います。', options: [{ op: 'A', value: 'の', }, { op: 'B', value: 'と', }, { op: 'C', value: 'は', }, { op: 'D', value: 'が', }], correctAns: ['B'] },
{ question: '壁（　）　スイッチが　あります。', options: [{ op: 'A', value: 'の', }, { op: 'B', value: 'の　うえに', }, { op: 'C', value: 'の　そとに', }, { op: 'D', value: 'に', }], correctAns: ['D'] },
{ question: '李さんの　傘は　どこ（　）。', options: [{ op: 'A', value: 'に　ありますか', }, { op: 'B', value: 'が　ありますか', }, { op: 'C', value: 'にですか', }, { op: 'D', value: 'がですか', }], correctAns: ['A'] },
{ question: 'ー美術館は　どこに　ありますか。\n－（　）、あそこです。', options: [{ op: 'A', value: 'あのう', }, { op: 'B', value: 'ええと', }, { op: 'C', value: 'あっ', }, { op: 'D', value: 'えっ', }], correctAns: ['B'] },
{ question: '（　）は　体育館に　います。', options: [{ op: 'A', value: '本', }, { op: 'B', value: 'サッカーボール', }, { op: 'C', value: '李さん', }, { op: 'D', value: '李さんの　ボール', }], correctAns: ['C'] },
{ question: '居間に　だれ（　）　いません。', options: [{ op: 'A', value: 'か', }, { op: 'B', value: 'が', }, { op: 'C', value: 'は', }, { op: 'D', value: 'も', }], correctAns: ['D']}],
},
  {
    unit: "U1", section: "UR",
    words: [{ word: "げんかん", property: "名", meaning: "玄关，门厅", },
    { word: "ろうか", property: "名", meaning: "走廊", },
    { word: "トイレ", property: "名", meaning: "卫生间，厕所", },
    { word: "よくしつ", property: "名", meaning: "浴室，洗澡间", },
    { word: "せんめんじょ", property: "名", meaning: "盥洗室", },
    { word: "だいどころ", property: "名", meaning: "厨房", },
    { word: "いま", property: "名", meaning: "起居室", },
    { word: "しんしつ", property: "名", meaning: "卧室", },
    { word: "わしつ", property: "名", meaning: "日式房间", },
    { word: "ベランダ", property: "名", meaning: "阳台", },
    { word: "にわ", property: "名", meaning: "院子", },
    { word: "やね", property: "名", meaning: "屋顶，房顶", },
    { word: "ボスト", property: "名", meaning: "信箱", },
    { word: "ガレージ", property: "名", meaning: "汽车房，车库", },
    { word: "ドア", property: "名", meaning: "门", },
    { word: "まど", property: "名", meaning: "窗户", },
    { word: "カーテン", property: "名", meaning: "窗帘", },
    { word: "エアコン", property: "名", meaning: "空调", },
    { word: "ソファー", property: "名", meaning: "沙发", },
    { word: "テーブル", property: "名", meaning: "桌子", },
    { word: "じゅうたん", property: "名", meaning: "地毯", },
    { word: "フローリング", property: "名", meaning: "木质地板", },
    { word: "でんわ", property: "名", meaning: "电话", },
    { word: "リモコン", property: "名", meaning: "遥控器", },
    { word: "ごみばこ", property: "名", meaning: "垃圾箱", },
    { word: "ほんだな", property: "名", meaning: "书架", },
    { word: "ビデオ", property: "名", meaning: "录像机", },
    { word: "まないた", property: "名", meaning: "切菜板", },
    { word: "ほうちょう", property: "名", meaning: "菜刀", },
    { word: "だいどころようせんざい", property: "名", meaning: "厨房用洗涤剂", },
    { word: "ふきん", property: "名", meaning: "抹布", },
    { word: "ながし", property: "名", meaning: "洗碗池，水池", },
    { word: "じゃぐち", property: "名", meaning: "水龙头", },
    { word: "なべ", property: "名", meaning: "锅", },
    { word: "オーブン", property: "名", meaning: "烤炉，烤箱", },
    { word: "でんしレンジ", property: "名", meaning: "微波炉", },
    { word: "しょっきだな", property: "名", meaning: "餐具柜，碗橱", },
    { word: "れいぞうこ", property: "名", meaning: "冰箱", },
    { word: "せんめんだい", property: "名", meaning: "洗脸台", },
    { word: "かがみ", property: "名", meaning: "镜子", },
    { word: "はブラシ", property: "名", meaning: "牙刷", },
    { word: "ドライヤー", property: "名", meaning: "吹风机", },
    { word: "タオル", property: "名", meaning: "毛巾", },
    { word: "シャワー", property: "名", meaning: "淋浴", },
    { word: "バスタブ", property: "名", meaning: "浴槽，浴缸", },
    { word: "せっけん", property: "名", meaning: "肥皂，香皂", },
    { word: "シャンプー", property: "名", meaning: "洗发水", },
    { word: "せんたくき", property: "名", meaning: "洗衣机", },
    { word: "かんそうき", property: "名", meaning: "烘干机", },
    { word: "たいじゅうけい", property: "名", meaning: "体重秤", },
    { word: "べんき", property: "名", meaning: "马桶", },
    { word: "トイレットペーパー", property: "名", meaning: "卫生纸", },
    { word: "ベッド", property: "名", meaning: "床", },
    { word: "まくら", property: "名", meaning: "枕头", },
    { word: "シーツ", property: "名", meaning: "床单", },
    { word: "かけぶとん", property: "名", meaning: "被子", },
    { word: "でんきスタンド", property: "名", meaning: "台灯", },
    { word: "めざましどけい", property: "名", meaning: "闹钟", },
    { word: "クローゼット", property: "名", meaning: "衣柜", },
    { word: "しょうじ", property: "名", meaning: "拉门，拉窗", },
    { word: "おしいれ", property: "名", meaning: "壁橱", },
    { word: "ふすま", property: "名", meaning: "隔扇", },
    { word: "ざぶとん", property: "名", meaning: "座垫", },
    { word: "たたみ", property: "名", meaning: "草垫，草席", }],
    exercises:
    [{ question: '1.（看汉字选假名）李さんは　東京（大学）の　学生です。', options: [{ op: 'A', value: 'たいかく', }, { op: 'B', value: 'だいかく', }, { op: 'C', value: 'たいがく', }, { op: 'D', value: 'だいがく', }], correctAns: ['D'] },
{ question: '2.これは　（3000）円です。　', options: [{ op: 'A', value: 'さんせん', }, { op: 'B', value: 'さんぜん', }, { op: 'C', value: 'よんせん', }, { op: 'D', value: 'よんぜん', }], correctAns: ['B'] },
{ question: '3.（机）の上に　地図が　あります。', options: [{ op: 'A', value: 'つくえ', }, { op: 'B', value: 'いす', }, { op: 'C', value: 'き', }, { op: 'D', value: 'いき', }], correctAns: ['A'] },
{ question: '4.あれは　（家族）の　写真です。', options: [{ op: 'A', value: 'じゃそく', }, { op: 'B', value: 'じゃぞく', }, { op: 'C', value: 'かそく', }, { op: 'D', value: 'かぞく', }], correctAns: ['D'] },
{ question: '5.これは　だれの　（辞書）ですか。', options: [{ op: 'A', value: 'ししょ', }, { op: 'B', value: 'じしょ', }, { op: 'C', value: 'ししょう', }, { op: 'D', value: 'じしょう', }], correctAns: ['B'] },
{ question: '6.（受付）は　このビルの　3階に　あります。', options: [{ op: 'A', value: 'うっつけ', }, { op: 'B', value: 'うっけ', }, { op: 'C', value: 'うけつけ', }, { op: 'D', value: 'うけっつ', }], correctAns: ['C'] },
{ question: '7.（食堂）は　だれも　いません。', options: [{ op: 'A', value: 'しょくとう', }, { op: 'B', value: 'しょとう', }, { op: 'C', value: 'しょくどう', }, { op: 'D', value: 'しょどう', }], correctAns: ['C'] },
{ question: '8.よろしくお（願い）します。', options: [{ op: 'A', value: 'ねがい', }, { op: 'B', value: 'ねかい', }, { op: 'C', value: 'ちかい', }, { op: 'D', value: 'ちがい', }], correctAns: ['A'] },
{ question: '9.これは　（雑誌）です。', options: [{ op: 'A', value: 'ざし', }, { op: 'B', value: 'ざっし', }, { op: 'C', value: 'さし', }, { op: 'D', value: 'さっし', }], correctAns: ['B'] },
{ question: '10.これは　わたしの　（息子）です。', options: [{ op: 'A', value: 'むすめ', }, { op: 'B', value: 'おとめ', }, { op: 'C', value: 'むすこ', }, { op: 'D', value: 'おとな', }], correctAns: ['C'] },
{ question: '11.いすの　（下）に　猫が　います。', options: [{ op: 'A', value: 'うえ', }, { op: 'B', value: 'した', }, { op: 'C', value: 'なか', }, { op: 'D', value: 'そと', }], correctAns: ['B'] },
{ question: '12.私は　（一人）暮らしです。', options: [{ op: 'A', value: 'ひとり', }, { op: 'B', value: 'ふたり', }, { op: 'C', value: 'いちじん', }, { op: 'D', value: 'いちにん', }], correctAns: ['A'] },
{ question: '13.（看假名选汉字）あなたの　（じてんしゃ）は　どちらですか。', options: [{ op: 'A', value: '自動車', }, { op: 'B', value: '車', }, { op: 'C', value: '自転車', }, { op: 'D', value: '電話', }], correctAns: ['C'] },
{ question: '14.これは　名古屋の　お（みやげ）です、どうぞ。', options: [{ op: 'A', value: '名産', }, { op: 'B', value: '名産品', }, { op: 'C', value: '都産', }, { op: 'D', value: '土産', }], correctAns: ['D'] },
{ question: '15.会議室の　となりは　（としょしつ）です。', options: [{ op: 'A', value: '図書室', }, { op: 'B', value: '読書室', }, { op: 'C', value: '図書館', }, { op: 'D', value: '読書館', }], correctAns: ['A'] },
{ question: '16.あなたの　（そふ）は　おいくつですか。', options: [{ op: 'A', value: '祖父', }, { op: 'B', value: '祖母', }, { op: 'C', value: '母', }, { op: 'D', value: '父', }], correctAns: ['A'] },
{ question: '17.これは　（くるま）の　かぎです。', options: [{ op: 'A', value: '傘', }, { op: 'B', value: '本', }, { op: 'C', value: '家', }, { op: 'D', value: '車', }], correctAns: ['D'] },
{ question: '18.男の　人は　車の　（うしろ）に　います。', options: [{ op: 'A', value: '裏', }, { op: 'B', value: '後ろ', }, { op: 'C', value: '表', }, { op: 'D', value: '外', }], correctAns: ['B'] },
{ question: '19.これは　JC企画の（しゃちょう）です。', options: [{ op: 'A', value: '社員', }, { op: 'B', value: '社長', }, { op: 'C', value: '店員', }, { op: 'D', value: '店長', }], correctAns: ['B'] },
{ question: '20.（きょう）は　木曜日です。', options: [{ op: 'A', value: '今', }, { op: 'B', value: '今度', }, { op: 'C', value: '明日', }, { op: 'D', value: '今日', }], correctAns: ['D'] },
{ question: '21.（选词填空）わたしの　部屋は　8（　）に　あります。', options: [{ op: 'A', value: '階', }, { op: 'B', value: '本', }, { op: 'C', value: '阶', }, { op: 'D', value: '层', }], correctAns: ['A'] },
{ question: '22.林さんは　中国人ですか　（　）ですか。', options: [{ op: 'A', value: '中国', }, { op: 'B', value: '社員', }, { op: 'C', value: '日本人', }, { op: 'D', value: '学生', }], correctAns: ['C'] },
{ question: '23.はじめまして、私は　李です、（　）。', options: [{ op: 'A', value: 'すみません', }, { op: 'B', value: 'どうぞよろしく', }, { op: 'C', value: 'ありがとう', }, { op: 'D', value: 'こちらこそ', }], correctAns: ['B'] },
{ question: '24.父の　父は　（　）です。', options: [{ op: 'A', value: 'おとうさん', }, { op: 'B', value: 'おかあさん', }, { op: 'C', value: 'おじいさん', }, { op: 'D', value: 'おばあさん', }], correctAns: ['C'] },
{ question: '25.北京旅行社は　中国の（　）です。', options: [{ op: 'A', value: '学生', }, { op: 'B', value: '先生', }, { op: 'C', value: '社員', }, { op: 'D', value: '企業', }], correctAns: ['D'] },
{ question: '26.（　）は　日本の町です。', options: [{ op: 'A', value: '北京', }, { op: 'B', value: '横浜', }, { op: 'C', value: '犬', }, { op: 'D', value: '机', }], correctAns: ['B'] },
{ question: '27.マンションの　隣は　（　）です。', options: [{ op: 'A', value: 'ホテル', }, { op: 'B', value: 'カメラ', }, { op: 'C', value: 'フランス', }, { op: 'D', value: 'パソコン', }], correctAns: ['A'] },
{ question: '28.（同义句转换）あなたは　（何歳ですか）。', options: [{ op: 'A', value: 'いくらですか', }, { op: 'B', value: 'いつですか', }, { op: 'C', value: 'なんじですか', }, { op: 'D', value: 'おいくつですか', }], correctAns: ['D'] },
{ question: '29.李さんの　部屋は　（どこですか）。', options: [{ op: 'A', value: 'いくらですか', }, { op: 'B', value: 'どこにですか', }, { op: 'C', value: 'いくらに　ありますか', }, { op: 'D', value: 'どこに　ありますか', }], correctAns: ['D'] },
{ question: '30.受付は　（どこですか）。', options: [{ op: 'A', value: 'どちらですか。', }, { op: 'B', value: 'どらちですか', }, { op: 'C', value: 'どちらにですか', }, { op: 'D', value: 'どらちにですか', }], correctAns: ['A']},
{ question: '1.（填空题）ーあのひとは　（　）ですか。\nー小野さんです。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'どれ', }, { op: 'C', value: 'だれ', }, { op: 'D', value: 'どこ', }], correctAns: ['C'] },
{ question: '2.ーどうぞよろしく。\n－（　）、よろしく  おねがいします。', options: [{ op: 'A', value: 'わかりません', }, { op: 'B', value: 'こちらこそ', }, { op: 'C', value: 'そうです', }, { op: 'D', value: 'すみません', }], correctAns: ['B'] },
{ question: '3.ーこれは　だれのパソコンですか。\n－（　）は　李さんのです。', options: [{ op: 'A', value: 'これ', }, { op: 'B', value: 'それ', }, { op: 'C', value: 'あれ', }, { op: 'D', value: 'どれ', }], correctAns: ['B'] },
{ question: '4.ーあれは　（　）ですか。\nーあれは　病院です。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'どれ', }, { op: 'C', value: 'だれ', }, { op: 'D', value: 'どこ', }], correctAns: ['A'] },
{ question: '5.テーブルの　上に　本（　）あります。', options: [{ op: 'A', value: 'の', }, { op: 'B', value: 'か', }, { op: 'C', value: 'が', }, { op: 'D', value: 'に', }], correctAns: ['C'] },
{ question: '6.ーはじめまして、李です、（　）。\nーはじめまして。', options: [{ op: 'A', value: 'こちらこそ', }, { op: 'B', value: 'わかりません', }, { op: 'C', value: 'そうです', }, { op: 'D', value: 'よろしくおねがいします', }], correctAns: ['D'] },
{ question: '7.私は　一人暮らしです。妻（　）　子供（　）　いません。　', options: [{ op: 'A', value: 'か、か', }, { op: 'B', value: 'も、も', }, { op: 'C', value: 'は、は', }, { op: 'D', value: 'が、も', }], correctAns: ['B'] },
{ question: '8.（　）は　体育館に　います。', options: [{ op: 'A', value: '本', }, { op: 'B', value: 'サッカーボール', }, { op: 'C', value: '李さん', }, { op: 'D', value: '李さんの　ボール', }], correctAns: ['C'] },
{ question: '9.（　）は　あなたの　お母さんですか。', options: [{ op: 'A', value: 'どのなた', }, { op: 'B', value: 'どなた', }, { op: 'C', value: 'どのじん', }, { op: 'D', value: 'どじん', }], correctAns: ['B'] },
{ question: '10.ーこれは中国の名産品です、（　）。', options: [{ op: 'A', value: 'どうぞ', }, { op: 'B', value: 'どうも', }, { op: 'C', value: 'どう', }, { op: 'D', value: 'こちらこそ', }], correctAns: ['A'] },
{ question: '11.猫と　犬（　）　こどもは　庭に　います。', options: [{ op: 'A', value: 'が', }, { op: 'B', value: 'か', }, { op: 'C', value: 'と', }, { op: 'D', value: 'の', }], correctAns: ['C'] },
{ question: '12.ーこれは　（　）の　カメラですか。\nーわたしのです。', options: [{ op: 'A', value: 'なん', }, { op: 'B', value: 'なに', }, { op: 'C', value: 'どれ', }, { op: 'D', value: 'だれ', }], correctAns: ['D'] },
{ question: '13.図書館は　どこ（　）か。', options: [{ op: 'A', value: 'が　あります', }, { op: 'B', value: 'が　います', }, { op: 'C', value: 'に　あります', }, { op: 'D', value: 'に　います', }], correctAns: ['C'] },
{ question: '14.ーあなたは  大学（　）先生ですか。\n－はい、そうです。', options: [{ op: 'A', value: 'の', }, { op: 'B', value: 'に', }, { op: 'C', value: 'は', }, { op: 'D', value: 'では', }], correctAns: ['A'] },
{ question: '15.居間に　だれ（　）　いません。', options: [{ op: 'A', value: 'か', }, { op: 'B', value: 'が', }, { op: 'C', value: 'は', }, { op: 'D', value: 'も', }], correctAns: ['D'] },
{ question: '16.ー美術館は　どこに　ありますか。\n－（　）、あそこです。', options: [{ op: 'A', value: 'あのう', }, { op: 'B', value: 'ええと', }, { op: 'C', value: 'あっ', }, { op: 'D', value: 'えっ', }], correctAns: ['B'] },
{ question: '17.（排序）（　）（　）（★）（　） 、小野です。', options: [{ op: 'A', value: '吉田', }, { op: 'B', value: 'ありません', }, { op: 'C', value: '私は', }, { op: 'D', value: 'では', }], correctAns: ['D'] },
{ question: '18.小野さん（　）（　）（★）（　） 　ありますか。', options: [{ op: 'A', value: 'の', }, { op: 'B', value: 'は', }, { op: 'C', value: '家', }, { op: 'D', value: 'どこに', }], correctAns: ['B'] },
{ question: '19.JC企画ビルの　（　）（　）（★）（　）  。', options: [{ op: 'A', value: '地下鉄の', }, { op: 'B', value: 'あります', }, { op: 'C', value: '駅が', }, { op: 'D', value: '隣に', }], correctAns: ['C'] },
{ question: '20.ー吉田さんは　どこですか。\nー（　）（　）（★）（　）  。', options: [{ op: 'A', value: '吉田さんは', }, { op: 'B', value: 'に', }, { op: 'C', value: 'あります', }, { op: 'D', value: '庭', }], correctAns: ['B'] },
{question: '21.はじめまして、（　）（　）（★）（　） 。', options: [{ op: 'A', value: 'お願い', }, { op: 'B', value: 'どうぞ', }, { op: 'C', value: 'します', }, { op: 'D', value: 'よろしく', }], correctAns: ['A']}]
},
  {
    unit: "U2", section: "S1",
    words: [{ word: "にちようび", property: "名", meaning: "星期日" },
    { word: "げつようび", property: "名", meaning: "星期一" },
    { word: "かようび", property: "名", meaning: "星期二" },
    { word: "まいしゅう", property: "名", meaning: "每个星期" },
    { word: "まいにち", property: "名", meaning: "每天" },
    { word: "きんようび", property: "名", meaning: "星期五" },
    { word: "どようび", property: "名", meaning: "星期六" },
    { word: "おととい", property: "名", meaning: "前天" },
    { word: "きのう", property: "名", meaning: "昨天" },
    { word: "きょう", property: "名", meaning: "今天" },
    { word: "あした", property: "名", meaning: "明天" },
    { word: "あさって", property: "名", meaning: "后天" },
    { word: "せんしゅう", property: "名", meaning: "上个星期" },
    { word: "こんしゅう", property: "名", meaning: "这个星期" },
    { word: "らいしゅう", property: "名", meaning: "下个星期" },
    { word: "さらいしゅう", property: "名", meaning: "下下个星期" },
    { word: "きょねん", property: "名", meaning: "去年" },
    { word: "まいあさ", property: "名", meaning: "每天早上" },
    { word: "らいねん", property: "名", meaning: "明年" },
    { word: "まいばん", property: "名", meaning: "每天晚上" },
    { word: "いま", property: "名", meaning: "现在" },
    { word: "ごぜん", property: "名", meaning: "上午（午前）" },
    { word: "ごご", property: "名", meaning: "下午（午后）" },
    { word: "こんばん", property: "名", meaning: "今天晚上" },
    { word: "けさ", property: "名", meaning: "今天早上" },
    { word: "よる", property: "名", meaning: "晚上，夜里，夜晚" },
    { word: "ばん", property: "名", meaning: "晚上" },
    { word: "あさ", property: "名", meaning: "早晨" },
    { word: "がっこう", property: "名", meaning: "学校" },
    { word: "しけん", property: "名", meaning: "考试" },
    { word: "しごと", property: "名", meaning: "工作" },
    { word: "ちこく", property: "名", meaning: "迟到" },
    { word: "やすみ", property: "名", meaning: "休息" },
    { word: "しゅっちょう", property: "名", meaning: "出差" },
    { word: "けんしゅう", property: "名", meaning: "进修" },
    { word: "りょこう", property: "名", meaning: "旅行" },
    { word: "てんらんかい", property: "名", meaning: "展览会" },
    { word: "かんげいかい", property: "名", meaning: "欢迎会" },
    { word: "パーティー", property: "名", meaning: "联欢会" },
    { word: "おたく", property: "名", meaning: "府上，（您）家" },
    { word: "いつ", property: "疑", meaning: "什么时候" },
    { word: "やすみます", property: "动1", meaning: "休息" },
    { word: "はたらきます", property: "动1", meaning: "工作" },
    { word: "はじまります", property: "动1", meaning: "开始" },
    { word: "おわります", property: "动1", meaning: "结束" },
    { word: "おきます", property: "动2", meaning: "起床" },
    { word: "ねます", property: "动3", meaning: "睡觉" },
    { word: "べんきょうします", property: "动3", meaning: "学习" },
    { word: "いつも", property: "副", meaning: "经常，总是" },
    { word: "ペキンししゃ", property: "专", meaning: "北京分社" },
    { word: "こうべ", property: "专", meaning: "神户" },
    { word: "おはよう", property: "短语", meaning: "你早" },
      { word: "おととい", property: "名", meaning: "前天" },
      { word: "きのう", property: "名", meaning: "昨天" },
      { word: "きょう", property: "名", meaning: "今天" },
      { word: "あした", property: "名", meaning: "明天" },
      { word: "あさって", property: "名", meaning: "后天" },
      { word: "まいにち", property: "名", meaning: "每天" },
      { word: "おとといのあさ", property: "名", meaning: "前天早晨" },
      { word: "きのうのあさ", property: "名", meaning: "昨天早晨" },
      { word: "けさ", property: "名", meaning: "今天早上" },
      { word: "あしたのあさ", property: "名", meaning: "明天早晨" },
      { word: "あさってのあさ", property: "名", meaning: "后天早晨" },
      { word: "まいあさ", property: "名", meaning: "每天早上" },
      { word: "おとといのばん", property: "名", meaning: "前天早上" },
      { word: "ゆうべ", property: "名", meaning: "昨天晚上" },
      { word: "こんばん", property: "名", meaning: "今天晚上" },
      { word: "あしたのばん", property: "名", meaning: "明天晚上" },
      { word: "あさってのばん", property: "名", meaning: "后天晚上" },
      { word: "まいばん", property: "名", meaning: "每天晚上" },
      { word: "せんせんしゅう", property: "名", meaning: "上上个星期" },
      { word: "せんしゅう", property: "名", meaning: "上个星期" },
      { word: "こんしゅう", property: "名", meaning: "这个星期" },
      { word: "らいしゅう", property: "名", meaning: "下个星期" },
      { word: "さらいしゅう", property: "名", meaning: "下下个星期" },
      { word: "まいしゅう", property: "名", meaning: "每个星期" },
      { word: "せんせんげつ", property: "名", meaning: "上上个月" },
      { word: "せんげつ", property: "名", meaning: "上个月" },
      { word: "こんげつ", property: "名", meaning: "这个月" },
      { word: "らいげつ", property: "名", meaning: "下个月" },
      { word: "さらいげつ", property: "名", meaning: "下下个月" },
      { word: "まいつき", property: "名", meaning: "每个月" },
      { word: "おととし", property: "名", meaning: "前年" },
      { word: "きょねん", property: "名", meaning: "去年" },
      { word: "ことし", property: "名", meaning: "今年" },
      { word: "らいねん", property: "名", meaning: "明年" },
      { word: "さらいねん", property: "名", meaning: "后年" },
      { word: "まいとし", property: "名", meaning: "每年" },
      { word: "いちじ", property: "名", meaning: "1时" },
      { word: "にじ", property: "名", meaning: "2时" },
      { word: "さんじ", property: "名", meaning: "3时" },
      { word: "よじ", property: "名", meaning: "4时" },
      { word: "ごじ", property: "名", meaning: "5时" },
      { word: "ろくじ", property: "名", meaning: "6时" },
      { word: "しちじ", property: "名", meaning: "7时" },
      { word: "はちじ", property: "名", meaning: "8时" },
      { word: "くじ", property: "名", meaning: "9时" },
      { word: "じゅうじ", property: "名", meaning: "10时" },
      { word: "じゅういちじ", property: "名", meaning: "11时" },
      { word: "じゅうにじ", property: "名", meaning: "12时" },
      { word: "れいじ", property: "名", meaning: "0时" },
      { word: "なんじ", property: "名", meaning: "何时" },
      { word: "いっぷん", property: "名", meaning: "1分" },
      { word: "にふん", property: "名", meaning: "2分" },
      { word: "さんぷん", property: "名", meaning: "3分" },
      { word: "よんぷん", property: "名", meaning: "4分" },
      { word: "ごふん", property: "名", meaning: "5分" },
      { word: "ろっぷん", property: "名", meaning: "6分" },
      { word: "ななふん", property: "名", meaning: "7分" },
      { word: "はっぷん", property: "名", meaning: "8分" },
      { word: "きゅうふん", property: "名", meaning: "9分" },
      { word: "じゅっぷん", property: "名", meaning: "10分" },
      { word: "じゅういっぷん", property: "名", meaning: "11分" },
      { word: "じゅうごふん", property: "名", meaning: "15分" },
      { word: "さんじゅっぷん", property: "名", meaning: "30分" },
      { word: "よんじゅうごふん", property: "名", meaning: "45分" },
      { word: "なんぷん", property: "名", meaning: "几分" },
      { word: "はん", property: "名", meaning: "…点半" },
      { word: "にちようび", property: "名", meaning: "星期日" },
      { word: "げつようび", property: "名", meaning: "星期一" },
      { word: "かようび", property: "名", meaning: "星期二" },
      { word: "すいようび", property: "名", meaning: "星期三" },
      { word: "もくようび", property: "名", meaning: "星期四" },
      { word: "きんようび", property: "名", meaning: "星期五" },
      { word: "どようび", property: "名", meaning: "星期六" },
      { word: "なんようび", property: "名", meaning: "星期几" }],

    exercises: []
  }
]

const formatTime = date => {
  const year = date.getFullYear()
  const month = date.getMonth() + 1
  const day = date.getDate()
  const hour = date.getHours()
  const minute = date.getMinutes()
  const second = date.getSeconds()

  return [year, month, day].map(formatNumber).join('/') + ' ' + [hour, minute, second].map(formatNumber).join(':')
}

const formatNumber = n => {
  n = n.toString()
  return n[1] ? n : '0' + n
}

function getContext(unit, section) {
  for(var i = 0; i < data.length; i++)
    if(data[i].unit == unit && data[i].section == section) 
      return data[i];
}
module.exports = {
  formatTime: formatTime,
  getContext: getContext,
}
